# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true

# --- Project Identity ---
project-group=io.github.mcagents
git-org-name=MCAgents
git-repository=core

# --- Versioning ---
# Don't update project-version until ready for release
project-version=0.0.0
